name: Node.js CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: NPM install
      uses: bahmutov/npm-install@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: npm run build
      env:
        CI: false # TODO consistent with frontend but I don't think this matters
    - name: Check Build
      run: npm run run:built:test-run # this script runs the application without connecting the server or database, therefore it goes through all the imports and everything
    # - name: Test
    #   run: npm test
    #   env:
    #     CI: true
    - name: Check Build
      run: npm prune --production
      run: npm run run:built:test-run # this script runs the application without connecting the server or database, therefore it goes through all the imports and everything
